const revenue = [38446071.33,34887085.55,41971649.09,37958457.37,41764716.4,38987082.82,40527291.81,45252181.75,44615037.46,56359195.92,51583838.47,50745209];
const finance = [...revenue];
const exceptions = {2:{pipeline:41971649.09,finance:42457899.09,title:'Scope difference',body:'Finance includes an institutional order invoiced outside the till. Take this scope note back to Finance.'},6:{pipeline:40295160.11,finance:40527291.81,title:'Source gap',body:'Pune (S07) lost its till server for three days in July. Finance has the phoned-in number; the folder cannot.'},11:{pipeline:50745259.48,finance:50745209,title:'Rounding',body:'Finance rounds each bill to the rupee. This is a definition difference, not a pipeline defect.'}};
const fmt=(value)=>'₹'+(value/1000000).toFixed(2)+'M';
document.querySelectorAll('.nav-item').forEach((button)=>button.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach((item)=>item.classList.remove('active'));document.querySelectorAll('.view').forEach((view)=>view.classList.remove('active'));button.classList.add('active');document.getElementById(button.dataset.section).classList.add('active');window.scrollTo({top:0,behavior:'smooth'});}));
const spark=document.getElementById('sparkline'); const peak=Math.max(...revenue); revenue.forEach((value,index)=>{const bar=document.createElement('div');bar.className='spark-bar'+(value===peak?' peak':'');bar.style.height=`${(value/peak)*100}%`;bar.title=`2024-${String(index+1).padStart(2,'0')} ${fmt(value)}`;spark.appendChild(bar);});
const chart=document.getElementById('barChart'); revenue.forEach((value,index)=>{const group=document.createElement('div');group.className='bar-group';if(index===6)group.classList.add('selected');const pipeline=document.createElement('div');pipeline.className='bar pipeline';pipeline.style.height=`${(value/peak)*100}%`;const financeBar=document.createElement('div');financeBar.className='bar finance';financeBar.style.height=`${(finance[index]/peak)*100}%`;group.append(pipeline,financeBar);group.addEventListener('click',()=>selectMonth(index));chart.appendChild(group);});
function selectMonth(index){document.querySelectorAll('.bar-group').forEach((group)=>group.classList.remove('selected'));chart.children[index].classList.add('selected');const result=exceptions[index];const pipelineValue=result?.pipeline??revenue[index];const financeValue=result?.finance??finance[index];document.getElementById('selectedMonth').textContent=`2024 / ${String(index+1).padStart(2,'0')}`;document.getElementById('selectedPipeline').textContent=fmt(pipelineValue);document.getElementById('selectedFinance').textContent=fmt(financeValue);const disposition=document.getElementById('disposition');if(result){disposition.innerHTML=`<span class="warning">!</span><div><strong>${result.title}</strong><small>${result.body}</small></div>`;}else{disposition.innerHTML='<span class="warning" style="background:#dcefe0;color:#387762">✓</span><div><strong>Matches finance</strong><small>Same month, same number. No action required.</small></div>';}}
let exceptionIndex=6;document.getElementById('nextException').addEventListener('click',()=>{exceptionIndex=exceptionIndex===11?2:exceptionIndex===2?6:11;selectMonth(exceptionIndex);});
document.querySelectorAll('.period').forEach((button)=>button.addEventListener('click',()=>{document.querySelectorAll('.period').forEach((item)=>item.classList.remove('active'));button.classList.add('active');const march=button.dataset.period==='march';document.getElementById('priceValue').textContent=march?'₹41.97M':'₹56.36M';document.getElementById('priceMeta').textContent=march?'March · 2024 · authoritative revision history':'October · 2024 · authoritative revision history';}));